### ISSUE TITLE
Support setting global tags from labels, annotations, etc

### ISSUE THREAD

**Issue by philomory** [influxdata/telegraf-operator#44]
I'd like to be able to set global tags based on annotations/labels/k8s namespace/etc. More specifically, I'd like to define a class like this:

```yaml
classes:
  data:
    foo: |+
      [global_tags]
        hostname = "$HOSTNAME"
        nodename = "$NODENAME"
        app = "$KUBERNETES_LABEL_APP"
```

To be clear, obviously I can _already_ define a class like that, but it won't work because there's no way to get the environment variable `$KUBERNETES_LABEL_APP` populated in the Telegraf container. If I was creating the container myself I'd be able to do something like,
```
env:
  - name: KUBERNETES_LABEL_APP
    valueFrom:
      fieldRef:
        fieldPath: metadata.labels['app']
```
But there's no way to set up anything like that when the container is injected automatically by the Operator. 

As an alternative, being able to just specify `telegraf.influxdata.com/include-labels: 'app,whatever'` or `telegraf.influxdata.com/tags: 'app=foo,whatever=bar'` as an annotation and have the Operator automatically construct...

```toml
[global_tags]
app = "foo"
whatever = "bar"
```
...would also be pretty good, but I get the feeling that could get awkward to implement since you can't define the same table multiple times in a TOML document, so if the class defines a `[global_tags]` table as well then they'd clash.

**Comment by cbos** [comment]
Currently it is possible to get secrets as environment variable with:
> telegraf.influxdata.com/secret-env : allows adding secrets to the telegraf sidecar in the form of environment variables

`telegraf.influxdata.com/secret-env: my-secret`  results in:
```
envFrom:
    - secretRef:
        name: my-secret
        optional: true
```

What if this will be extended like this, I can probably implement it and create a PR:

`telegraf.influxdata.com/config-env: my-config`  results in:
```
envFrom:
    - configMapRef:
        name: my-config
        optional: true
```
Variables defined in the configMap can be used a variable in the telegraf config.
This can include information for the tags used in the [global]  section, or interval settings or any other type of configuration needed.

Next to that it would be nice to use information from the pod, as described here: https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/

`telegraf.influxdata.com/field-env: NAMESPACE=metadata.namespace,PODNAME=metadata.name,APP=metadata.labels['app']`  results in:
```
     env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PODNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
```

With these field you can then specify in you classes config:
```
[global_tags]
app = "$APP"
namespace = "$NAMESPACE"
```

If this proposal is OK, then I can give it a try and implement it and create a PR.
/cc @BondAnthony  @wojciechka

**Comment by wojciechka** [comment]
> If this proposal is OK, then I can give it a try and implement it and create a PR. /cc @BondAnthony @wojciechka

I really like where this is going, however, I would like to request a slightly different annotation scheme.

I think it would be better and easier to manage if the annotations would use a prefix and a specific form - such as `telegraf.influxdata.com/env-(how)-(variable name): (how specific information)`. So in your specific case it could be:

```
telegraf.influxdata.com/env-fieldref-NAMESPACE: "metadata.namespace"
telegraf.influxdata.com/env-fieldref-PODNAME: "metadata.name"
telegraf.influxdata.com/env-fieldref-APP: "metadata.labels['app']"
```

I think this would make the annotation more readable.

Would this idea work for you @cbos ?

**Comment by cbos** [comment]
@wojciechka
That is fine with me. That's why I first posted a proposal rather then first implementing it. Then we can discuss about it to get the solution clear. 

Only the naming is then different from the current available `secret-env`.

But it gives options to implement for secret and config map an option to select a single item instead of the whole.

**Comment by wojciechka** [comment]
> @wojciechka That is fine with me. That's why I first posted a proposal rather then first implementing it. Then we can discuss about it to get the solution clear.

Actually, let me start by thanking you for doing it this way and also for willingness to implement this. We really appreciate it :)

> Only the naming is then different from the current available `secret-env`.
> 
> But it gives options to implement for secret and config map an option to select a single item instead of the whole.

Perhaps those could be implemented as `/env-configmapkeyref-(variable name)` and `/env-secretkeyref-(variable name)`, where the value would be `(secret name).(key name)` and would translate to:

```
envFrom:
  - name: (variable name)
    valueFrom:
      configMapKeyRef: # or secretKeyRef respectively
        name: (secret name)
        key: (key name)
```

This would make it easier to import a single variable and would not require that config map / secret share the exact same names.

I'm not sure about whether this should be `optional` - I would expect telegraf to not work properly if it's missing one or more variables referenced from the configuration. But I'm ok with keeping it optional.
