### ISSUE TITLE
arch to image mapping with nodeSelector

### ISSUE THREAD

**Issue by pokebadgerswithspoon** [influxdata/telegraf-operator#67]
`telegraf-operator` is an amd64 image, `telegraf` supports multiarch

Would it be a good idea to add nodeSelector to telegraf-operator deployment part of https://github.com/influxdata/telegraf-operator/blob/master/deploy/dev.yml ?

Like this
```
    spec:
      serviceAccountName: telegraf-operator
      nodeSelector:
        kubernetes.io/arch: amd64      
```

So operator itself would require amd64 part of a cluster.

##### What products and version are you using?

telegraf-operator:1.3
