### ISSUE TITLE
Add `global_tags` annotation

### ISSUE THREAD

**Issue by mkmik** [influxdata/telegraf-operator#82]
Oftentimes you don't need a brand new class. All you want is to add a common tag to all the metrics emitted by a given pod.

## Proposal

```
annotations:
  telegraf.influxdata.com/global-tag-literal-region: us-east1
  telegraf.influxdata.com/global-tag-fieldref-ns: metadata.namespace
  telegraf.influxdata.com/global-tag-configmapkeyref-foo: bar.baz
```

equivalent to use this generated config:
```toml
    [global_tags]
      region = "us-east1"
      ns = "myns"
      foo = "quz"
```

(the implementation may choose to use some intermediate env vars if so desired)
