### ISSUE TITLE
Should metric-version be a string?

### ISSUE THREAD

**Issue by stianlagstad** [influxdata/telegraf-operator#93]
I'm using the telegraf operator to get prometheus metrics from my pod into influxdb. With `telegraf.influxdata.com/metric-version: "2"` things work, but with `telegraf.influxdata.com/metric-version: 2` (as the readme currently says), I get an error on `kubectl apply -f`. The error I get:
> cannot convert int64 to string

Version info:
```
➜  kubectl version -o yaml
clientVersion:
  buildDate: "2022-03-16T15:58:47Z"
  compiler: gc
  gitCommit: c285e781331a3785a7f436042c65c5641ce8a9e9
  gitTreeState: clean
  gitVersion: v1.23.5
  goVersion: go1.17.8
  major: "1"
  minor: "23"
  platform: linux/amd64
serverVersion:
  buildDate: "2022-01-25T21:19:12Z"
  compiler: gc
  gitCommit: 816c97ab8cff8a1c72eccca1026f7820e93e0d25
  gitTreeState: clean
  gitVersion: v1.23.3
  goVersion: go1.17.6
  major: "1"
  minor: "23"
  platform: linux/amd64
```
Using `dev.yml` from v1.3.6 of the telegraf-operator.
